services:
  postgres:
    image: "postgres:17.4-alpine3.21"
    env_file:
      - ./postgres/.env
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  fastify:
    build: ./packages/fastify
    env_file:
      - ./packages/fastify/.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  db-data: